name: my_dbt_project
version: '1.0'
config-version: 2

profile: my_dbt_profile

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  my_dbt_project:
    +materialized: view
